spring:
  application:
    name: fx-service

  datasource:
    url: jdbc:postgresql://localhost:5432/jsb_cbs_unified?currentSchema=fx_service
    username: jsb
    password: jsb

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: fx_service

  flyway:
    enabled: true
    schemas: fx_service
    default-schema: fx_service

  cache:
    type: simple

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fx-service
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics