spring:
  application:
    name: ledger-service

  datasource:
    url: jdbc:postgresql://localhost:5432/jsb_cbs_unified?currentSchema=ledger_service
    username: jsb
    password: jsb

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: ledger_service

  flyway:
    enabled: true
    schemas: ledger_service
    default-schema: ledger_service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ledger-service
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics